from telebot import types

def home_key():
    key = types.ReplyKeyboardMarkup(resize_keyboard=True,row_width=2)
    btn1 = types.KeyboardButton(text="⏰Nomoz vaqti")
    btn2 = types.KeyboardButton(text="📖Qo'llanma")
    btn3 = types.KeyboardButton(text="💬Bog'lanish")
    key.add(btn1,btn2,btn3)
    return key


def location_keys():
    key = types.InlineKeyboardMarkup(row_width=3)
    btn1 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn2 = types.InlineKeyboardButton(text="🌆Buxoro",callback_data="buxoro")
    btn3 = types.InlineKeyboardButton(text="🌆Farg'ona",callback_data="andijon")
    btn4 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn5 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn6 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn7 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn8 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn9 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn10 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn11 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn12 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn13 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn14 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn15 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn16 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn17 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn18 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn19 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn20 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn21 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn22 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn23 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn24 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn25 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn26 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn27 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn28 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn29 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn30 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn31 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn32 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn33 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn34 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn35 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn36 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn37 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn38 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn39 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn40 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn41 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn42 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn43 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn44 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn45 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn46 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn47 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn48 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn49 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn50 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn51 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn52 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn53 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn54 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn55 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn56 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn57 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn58 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn59 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn60 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn61 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn62 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn63 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn64 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn65 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn66 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn67 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn68 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn69 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn70 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn71 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn72 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn73 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn74 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn75 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn76 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn77 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")

    btn78 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn79 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn80 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn81 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn82 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn83 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn84 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn85 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn86 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn87 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn88 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn89 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    btn90 = types.InlineKeyboardButton(text="🌆Andijon",callback_data="andijon")
    key.add(btn1,btn2,btn3,btn4,btn5,btn6,btn7,btn8,btn9,btn10,btn11,btn12,btn13,btn14,btn15,btn16,btn17,btn18,btn19,btn20,btn21,btn22,btn23,btn24,btn25,btn26,btn27,btn28,btn29,btn30,btn31,btn32,btn33,btn34,btn35,btn36,btn37,btn38,btn39,btn40,btn41,btn42,btn43,btn44,btn45,btn46,btn47,btn48,btn49,btn50,btn51,btn52,btn53,btn54,btn55,btn56,btn57,btn58,btn59,btn60,btn61,btn62,btn63,btn64,btn65,btn66,btn67,btn68,btn69,btn70,btn71,btn72,btn73,btn74,btn75,btn76,btn77,btn78,btn79,btn80,btn81,btn82,btn83,btn84,btn85,btn86,btn87,btn88,btn89,btn90)


    return key 
def admin_keys():
    key = types.ReplyKeyboardMarkup(resize_keyboard=True,row_width=2)
    btn1 = types.KeyboardButton(text="Send User")
    btn2 = types.KeyboardButton(text="Send Group")
    btn3 = types.KeyboardButton(text="Forward User")
    btn4 = types.KeyboardButton(text="Forward Group")
    btn5 = types.KeyboardButton(text="Stat")
    key.add(btn1,btn2,btn3,btn4,btn5)
    return key
