all_locations_list = [
    'andijon',
    'angren',
    'bekobod',
    'boysun',
    'buxoro',
    'gazli',
    'guliston',
    'denov',
    'dehqonobod',
    "do'stlik",
    'jizzax',
    'zarafshon',
    'zomin',
    'konimex',
    "marg'ilon",
    'mingbuloq',
    'muborak',
    "mo'ynoq",
    'navoiy',
    'namangan',
    'nukus',
    'nur ota',
    'olti ariq',
    'paxta obod',
    'rishton',
    'samarqand',
    'termiz',
    'toshkent',
    "to'rt ko'l",
    'urganch',
    'urgut',
    'uchquduq',
    "uchqo'rg'on",
    "farg'ona",
    "xiva",
    "xonobod",
    "xonqa",
    "xo'ja obod",
    "chortoq",
    "chust",
    "shahrixon",
    "sherobod",
    "yangi bozor",
    "g'alla orol",
    "qarshi",
    "qora ko'l",
    "quva",
    "qo'ng'irot",
    "qo'qon"
]

all_locations = {
    'andijon':"andijon",
    'angren':"angren",
    'bekobod':"bekobod",
    'boysun':"boysun",
    'buxoro':"buxoro",
    'gazli':"gazli",
    'guliston':"guliston",
    'denov':"denov",
    'dehqonobod':"dehqonobod",
    "do'stlik":"dostlik",
    'jizzax':"jizzax",
    'zarafshon':"zarafshon",
    'zomin':"zomin",
    'konimex':"konimex",
    "marg'ilon":"margilon",
    'mingbuloq':"mingbuloq",
    'muborak':"muborak",
    "mo'ynoq":"moynoq",
    'navoiy':"navoiy",
    'namangan':"namangan",
    'nukus':"nukus",
    'nur ota':"nurota",
    'olti ariq':"oltiariq",
    'paxta obod':"paxtaobod",
    'rishton':"rishton",
    'samarqand':"samarqand",
    'termiz':"termiz",
    'toshkent':"toshkent",
    "to'rt ko'l":"tortkol",
    'urganch':"urganch",
    'urgut':"urgut",
    'uchquduq':"uchquduq",
    "uchqo'rg'on":"uchqorgon",
    "farg'ona":"fargona",
    "xiva":"xiva",
    "xonobod":"xonobod",
    "xonqa":"xonqa",
    "xo'ja obod":"xojaobod",
    "chortoq":"chortoq",
    "chust":"chust",
    "shahrixon":"shahrixon",
    "sherobod":"sherobod",
    "yangi bozor":"yangibozor",
    "g'alla orol":"gallaorol",
    "qarshi":"qarshi",
    "qora ko'l":"qorakol",
    "quva":"quva",
    "qo'ng'irot":"qongirot",
    "qo'qon":"qoqon"    
}